xUnit logging support
q2ebanking/boa-constrictor pull request #248
Opened 2022-12-13 23:50 UTC by thePantz

## Description

> Changes for #227 
- Added project `Boa.Constrictor.Xunit` for items that improve [xUnit](https://xunit.net/) support
- Added project `Boa.Constrictor.Xunit.UnitTests`
- Added XunitLogger to support the use of `ITestOutputHelper`
- Added `XunitLoggerTests`

## Testing

> Built and executed unit tests. Based my test scenarios off of `ConsoleLoggerTests`

## Checklist

- [X] I agree to follow Boa Constrictor's [Code of Conduct](https://q2ebanking.github.io/boa-constrictor/contributing/code-of-conduct/).
- [X] I read Boa Constrictor's [Contributing Code](https://q2ebanking.github.io/boa-constrictor/contributing/contributing-code/) guide.
- [X] I successfully built the .NET solution with no errors or new warnings.
- [X] I successfully ran both the unit tests and the example tests.
- [X] I updated the [appropriate changelogs](CHANGELOG.md) with concise descriptions of these changes.
- [X] I added documentation for these changes (if appropriate).

2022-12-14 05:17 UTC, AutomationPanda requested changes
Excellent work. In addition to the few minor requests, please also add a `Boa.Constrictor.Xunit` package to the `nuget-push.yml` GitHub workflow so we can publish this package automatically once this pull request is merged. (Don't forget to update the changelog with the package version, too.

2022-12-14 05:17 UTC, AutomationPanda commented on Boa.Constrictor.Xunit.UnitTests/Logging/Loggers/XunitLoggerTest.cs
> +using Boa.Constrictor.Screenplay;
Pet peeve, but please alphabetize all imports.

2022-12-14 05:17 UTC, AutomationPanda commented on Boa.Constrictor.Xunit.UnitTests/Logging/Loggers/XunitLoggerTest.cs
> +            Logger.Info("moto");
I love it.

2022-12-14 05:17 UTC, AutomationPanda commented on Boa.Constrictor.Xunit.UnitTests/Boa.Constrictor.Xunit.UnitTests.csproj
> +    <PackageReference Include="xunit" Version="2.4.2" />
Note: Other unit test projects use NUnit, but it is proper for this one (for obvious reasons) to use xUnit.net.

2022-12-14 15:40 UTC, thePantz commented
@AutomationPanda Awesome! Thanks for the feedback! I see I made some copy pasta 😅I'm busy for the next couple days but I'll circle back to this on Friday

2022-12-17 01:14 UTC, AutomationPanda commented on Boa.Constrictor.Xunit/Boa.Constrictor.Xunit.csproj
> +    <Authors>Keith Tremorin, Pandy Knight and the PrecisionLender SETs</Authors>
Righteous.

2022-12-17 01:17 UTC, AutomationPanda approved these changes
Excellent work, @thePantz! Thank you so much for your contribution to Boa Constrictor. Let me know if you'd like me to mail you some official Boa Constrictor stickers!

2022-12-17 01:17 UTC, merged

2022-12-18 15:36 UTC, thePantz commented
@AutomationPanda I'd love some stickers!

2022-12-18 17:20 UTC, CoffeeAtBedtime commented
👏