Update Switching to Frames
q2ebanking/boa-constrictor pull request #270
Opened 2024-01-26 16:37 UTC by Swatkins18

## Description [4.1.0] - 2024-01-26
- Update `SwitchFrames` to have a property that controls whether or not to start from DefaultContent
- Add `SwitchIntoNestedFrames` Task

## Testing
Ran all the Boa Constrictor Tests
![image](https://github.com/q2ebanking/boa-constrictor/assets/75698467/188d1c98-ecba-42c4-8cfa-18dfa08e42ff)

Packed the alpha package locally, installed it in a test automation solution, then ran a test that utilized switching into nested frames (which uses the new code in `SwitchFrames` also) and observed that it was successful.
![image](https://github.com/q2ebanking/boa-constrictor/assets/75698467/c4dd53ad-2043-4847-8eb1-5ff2c1d59c4a)

Here is a fraction of the logs generated from that test run:
![image](https://github.com/q2ebanking/boa-constrictor/assets/75698467/a460da01-ef7a-4665-a0a8-1d580f642155)

Additionally, I ran a sample of 6 other tests that use `SwitchFrames` to verify that the update to the class.

## Checklist

- [x] I agree to follow Boa Constrictor's [Code of Conduct](https://q2ebanking.github.io/boa-constrictor/contributing/code-of-conduct/).
- [x] I read Boa Constrictor's [Contributing Code](https://q2ebanking.github.io/boa-constrictor/contributing/contributing-code/) guide.
- [x] I successfully built the .NET solution with no errors or new warnings.
- [x] I successfully ran both the unit tests and the example tests.
- [x] I updated the [appropriate changelogs](CHANGELOG.md) with concise descriptions of these changes.
- [x] I added documentation for these changes (if appropriate).

2024-01-26 22:08 UTC, Swatkins18 commented
Working on moving the nested frames functionality into `SwitchFrame`. But the app I'm testing is experiencing login issues right now, so I can't test. I'm planning to pick this back up next week.

2024-01-29 19:46 UTC, Swatkins18 commented
Retested BC tests
![image](https://github.com/q2ebanking/boa-constrictor/assets/75698467/93ff5554-6b5d-4c7d-aebb-3e711dc79c36)

2024-01-29 19:57 UTC, pl-shernandez approved these changes

2024-01-31 21:21 UTC, AutomationPanda requested changes

2024-01-31 21:21 UTC, AutomationPanda commented on Boa.Constrictor.Selenium/Tasks/SwitchFrame.cs
> +            Locators.Equals(frame.Locators) &&
`Equals` on a list will check references, not values.

https://stackoverflow.com/questions/22173762/check-if-two-lists-are-equal

2024-01-31 21:34 UTC, merged